import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-violet-500 mx-32 my-5 p-4 flex justify-center gap-10 rounded">
          <Link className="text-white font-semibold text-3xl " href="/">
            Home
          </Link>
          <Link className="text-white font-semibold text-3xl " href="/shop">
            Shop
          </Link>
        </nav>
        <main className="h-96">{children}</main>
      </body>
    </html>
  );
}
